version: "3"

services:
  mongo:
    container_name: doof_mongo
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    #restart: always
    volumes:
      - /root/mongodata

  app:
    build: .
    container_name: doof_api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
