version: "3"


networks:
  my-network:
    driver: bridge

services:
  mongo:
    container_name: doof_mongo
    image: mongo
    env_file:
      - .env
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      #- MONGO_INITDB_DATABASE=${MONGODB_DB}
    restart: always
    networks:
      - my-network
    volumes:
      - /root/mongodata:/data/db
     

  app:
    build: .
    container_name: doof_api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network
    links:
      - mongo
    depends_on:
      - mongo
    restart: always

