version: "3"

services:
  mongo:
    container_name: doof_mongo
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    restart: always

  app:
    build: .
    container_name: doof_api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    restart: always

  doof_client:
    image: pedrobernardosanchez/doofclientui-doof_client:latest
    container_name: doof_client
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RESTAURANT_NAME=${VITE_RESTAURANT_NAME}
      - VITE_RESTAURANT_TIME=${VITE_RESTAURANT_TIME}
    restart: always

  doof_manager:
    image: pedrobernardosanchez/doofmanagerui-doof_manager:latest
    container_name: doof_manager
    env_file:
      - .env
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_RESTAURANT_NAME=${VITE_RESTAURANT_NAME}
      - VITE_RESTAURANT_TIME=${VITE_RESTAURANT_TIME}
    restart: always
