version: "3"

services:
  mongo:
    container_name: doof_mongo
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    restart: always

  app:
    build: .
    container_name: doof_api
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    restart: always

  doof_client_image:
    image: pedrobernardosanchez/doof_client_image
    container_name: doof_client_image
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_RESTAURANT_NAME=${REACT_APP_RESTAURANT_NAME}
      - REACT_APP_RESTAURANT_TIME=${REACT_APP_RESTAURANT_TIME}

  doof_manager_image:
    image: pedrobernardosanchez/doof_manager_image
    container_name: doof_managerui_image
    env_file:
      - .env
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_RESTAURANT_NAME=${REACT_APP_RESTAURANT_NAME}
      - REACT_APP_RESTAURANT_TIME=${REACT_APP_RESTAURANT_TIME}
